/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAssetsRouteImport } from './routes/api/assets'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiKeysRouteImport } from './routes/api/keys'
import { Route as ApiLookupRouteImport } from './routes/api/lookup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsRoute = ApiAssetsRouteImport.update({
  id: '/api/assets',
  path: '/api/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api/keys',
  path: '/api/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLookupRoute = ApiLookupRouteImport.update({
  id: '/api/lookup',
  path: '/api/lookup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/assets': typeof ApiAssetsRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/keys': typeof ApiKeysRoute
  '/api/lookup': typeof ApiLookupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/assets': typeof ApiAssetsRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/keys': typeof ApiKeysRoute
  '/api/lookup': typeof ApiLookupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/assets': typeof ApiAssetsRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/keys': typeof ApiKeysRoute
  '/api/lookup': typeof ApiLookupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/assets' | '/api/history' | '/api/keys' | '/api/lookup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/assets' | '/api/history' | '/api/keys' | '/api/lookup'
  id:
    | '__root__'
    | '/'
    | '/api/assets'
    | '/api/history'
    | '/api/keys'
    | '/api/lookup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAssetsRoute: typeof ApiAssetsRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiKeysRoute: typeof ApiKeysRoute
  ApiLookupRoute: typeof ApiLookupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets': {
      id: '/api/assets'
      path: '/api/assets'
      fullPath: '/api/assets'
      preLoaderRoute: typeof ApiAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys': {
      id: '/api/keys'
      path: '/api/keys'
      fullPath: '/api/keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lookup': {
      id: '/api/lookup'
      path: '/api/lookup'
      fullPath: '/api/lookup'
      preLoaderRoute: typeof ApiLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAssetsRoute: ApiAssetsRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiKeysRoute: ApiKeysRoute,
  ApiLookupRoute: ApiLookupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
